org.gradle.jvmargs=-Xmx4g
org.gradle.caching=true
org.gradle.configuration-cache=true

android.useAndroidX=true
android.experimental.androidTest.builtin_test_platform=true
android.experimental.enableScreenshotTest=true
android.experimental.testSuiteSupport=true
android.onlyEnableUnitTestForTheTestedBuildType=false
