plugins {
    id("io.github.gmazzo.test.aggregation")
    id("base")
}

allprojects {
    apply(plugin: "jacoco")
    apply(plugin: "io.github.gmazzo.test.aggregation")
    rootProject.dependencies { aggregateTestsFrom(project) }

    jacoco.toolVersion = "0.8.12"

    tasks.withType(Test).configureEach {
        useJUnit()
    }

    tasks.withType(JacocoReport).configureEach {
        reports.xml.required = true
    }
}
