plugins {
    id("java-library")
}

apply(from: "../module-convention.gradle")

java {
    registerFeature("foo") {
        usingSourceSet(sourceSets.maybeCreate("foo"))
    }
    registerFeature("bar") {
        usingSourceSet(sourceSets.maybeCreate("bar"))
    }
}

testing.suites {
    testFoo(JvmTestSuite) {
        aggregatedTestCoverage.addTestSuite(sourceSets.foo, it)
    }
    testBar(JvmTestSuite){
        aggregatedTestCoverage.addTestSuite(sourceSets.bar, it)
    }
}

dependencies {
    testImplementation("junit:junit:4.13")
}
