plugins {
    id("com.android.library")
}

android {
    namespace = "org.test.lib"

    compileSdk = 34

    buildTypes.debug.enableUnitTestCoverage = true
    buildTypes.debug.enableAndroidTestCoverage = true

    testOptions.managedDevices.localDevices {
        register("emulator") {
            device = "Pixel 10"
            apiLevel = 33
            systemImageSource = "aosp_atd"
        }
    }
}
